/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2023-07-06 13:00:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class treeList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/satyendra.CORP/Desktop/sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SecureBankingCore/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/C:/Users/satyendra.CORP/Desktop/sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SecureBankingCore/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1465528008000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1489741376257L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar", Long.valueOf(1502866017735L));
    _jspx_dependants.put("jar:file:/C:/Users/satyendra.CORP/Desktop/sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SecureBankingCore/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/C:/Users/satyendra.CORP/Desktop/sts/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SecureBankingCore/WEB-INF/lib/spring-webmvc-4.3.0.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1465528008000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\"> \r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/bootstrap-treeview.css />\r\n");
      out.write("<script type=\"text/javascript\"src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/bootstrap-treeview.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tdebugger;\r\n");
      out.write("\t  var treeData='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${treeData}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("        var $searchableTree = $('#treeview-searchable').treeview({\r\n");
      out.write("        \t data: treeData, \r\n");
      out.write("   \t\t  showTags: true,\r\n");
      out.write("   \t\t  color: \"#428bca\",\r\n");
      out.write("      \t\texpandIcon: \"glyphicon glyphicon-stop\",\r\n");
      out.write("            collapseIcon: \"glyphicon glyphicon-unchecked\",\r\n");
      out.write("            nodeIcon: \"glyphicon glyphicon-user\", \r\n");
      out.write("            onhoverColor: \"#e3a122\",\r\n");
      out.write("            borderColor: \"red\",\r\n");
      out.write("            selectedColor: \"#428bca\",\r\n");
      out.write("            selectedBackColor: \"#fcdb9a\",\r\n");
      out.write("          });\r\n");
      out.write("          var search = function(e) {\r\n");
      out.write("            var pattern = $('#input-search').val();\r\n");
      out.write("            var options = {\r\n");
      out.write("              ignoreCase: true,\r\n");
      out.write("              exactMatch: false,\r\n");
      out.write("              revealResults: true\r\n");
      out.write("            };\r\n");
      out.write("            var results = $searchableTree.treeview('search', [ pattern, options ]);\r\n");
      out.write("            var output = '<p>' + results.length + ' matches found</p>';\r\n");
      out.write("            $.each(results, function (index, result) {\r\n");
      out.write("              output += '<p>- ' + result.text + '</p>';\r\n");
      out.write("            });\r\n");
      out.write("            $('#search-output').html(output);\r\n");
      out.write("          }\r\n");
      out.write("          $('#btn-search').on('click', search);\r\n");
      out.write("          $('#input-search').on('keyup', search);\r\n");
      out.write("          $('#btn-clear-search').on('click', function (e) {\r\n");
      out.write("            $searchableTree.treeview('clearSearch');\r\n");
      out.write("            $('#input-search').val('');\r\n");
      out.write("            $('#search-output').html('');\r\n");
      out.write("          });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"heading-inner\">\r\n");
      out.write("\t     <!-- ****************************************** Form Heading  ******************************* -->\r\n");
      out.write("\t                      <h1 class=\"pull-left\">Tree View</h1>\r\n");
      out.write("\t                      <div class=\"clearfix\"></div>\r\n");
      out.write("\t                          <hr>\r\n");
      out.write("\t                      </div>\r\n");
      out.write("\t                      \r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xs-12 col-sm-12 col-md-4 col-lg-4 mt\"></div>\r\n");
      out.write("         <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-8 mt \">\r\n");
      out.write("          <!-- <form> -->\r\n");
      out.write("            <div class=\"form-group \" align=\"right\">\r\n");
      out.write("            \r\n");
      out.write("            <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("              <label for=\"input-search\" class=\"sr-only\">Search Tree:</label>\r\n");
      out.write("              <input type=\"input\" class=\"form-control\" id=\"input-search\" placeholder=\"Type to search...\" value=\"\"></td>\r\n");
      out.write("              <td>&nbsp;&nbsp; <button type=\"button\" class=\"btn btn-info\" id=\"btn-clear-search\">Clear</button></td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               </table>\r\n");
      out.write("            </div>\r\n");
      out.write(" <!--            <div class=\"checkbox\">\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" class=\"checkbox\" id=\"chk-ignore-case\" value=\"false\">\r\n");
      out.write("                Ignore Case\r\n");
      out.write("              </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"checkbox\">\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" class=\"checkbox\" id=\"chk-exact-match\" value=\"false\">\r\n");
      out.write("                Exact Match\r\n");
      out.write("              </label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"checkbox\">\r\n");
      out.write("              <label>\r\n");
      out.write("                <input type=\"checkbox\" class=\"checkbox\" id=\"chk-reveal-results\" value=\"false\">\r\n");
      out.write("                Reveal Results\r\n");
      out.write("              </label>\r\n");
      out.write("            </div> -->\r\n");
      out.write("           \r\n");
      out.write("          <!-- </form> -->\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12 mt \">\r\n");
      out.write("        <div class=\"col-xs-12 col-sm-12 col-md-8 col-lg-8\">\r\n");
      out.write("          <h1>Tree</h1>\r\n");
      out.write("          <div id=\"treeview-searchable\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-sm-4\">\r\n");
      out.write("          <h1>Results</h1>\r\n");
      out.write("          <div id=\"search-output\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
